base_url = "https://eduardoklosowski.github.io/blog/"

title = "Blog Eduardo Klosowski"

default_language = "pt-BR"

taxonomies = [
    {name = "tags", paginate_by = 10},
    {name = "linguagens", paginate_by = 10},
]

generate_feed = true
feed_filename = "atom.xml"

compile_sass = true
minify_html = false


[markdown]

highlight_code = true
highlight_theme = "charcoal"

external_links_target_blank = true


[extra]

author = "Eduardo Klosowski"

sidebar_links = [
    {name = "GitHub", url = "https://github.com/eduardoklosowski", external = true},
    {name = "Twitter", url = "https://twitter.com/eduklosowski", external = true},
    {name = "Twitch", url = "https://twitch.tv/eduardoklosowski", external = true},
    {name = "asciinema", url = "https://asciinema.org/~eduardoklosowski", external = true},
]
