base_url = "https://eduardoklosowski.github.io/blog/"

title = "Blog Eduardo Klosowski"

default_language = "pt-BR"

taxonomies = [
    {name = "tags", paginate_by = 10},
    {name = "linguagens", paginate_by = 10},
]

generate_feed = true
feed_filename = "atom.xml"

compile_sass = true
minify_html = false


[markdown]

highlight_code = true
highlight_theme = "charcoal"

external_links_target_blank = true


[extra]

author = "Eduardo Klosowski"

sidebar_links = [
    {name = "GitHub", icon = "icons/github.svg", url = "https://github.com/eduardoklosowski", external = true},
    {name = "Twitter", icon = "icons/twitter.svg", url = "https://twitter.com/eduklosowski", external = true},
    {name = "Twitch", icon = "icons/twitch.svg", url = "https://twitch.tv/eduardoklosowski", external = true},
    {name = "asciinema", icon = "icons/asciinema.svg", url = "https://asciinema.org/~eduardoklosowski", external = true},
    {name = "DEV", icon = "icons/dev.svg", url = "https://dev.to/eduardoklosowski", external = true},
]

analytics_cloudflare = "73939fe3b7984f859c0427bc6c693927"
analytics_gtag = "G-15ZW1NJTDE"
