name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Setup do GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Setup do Zola
        run: wget -O - "https://github.com/getzola/zola/releases/download/v0.17.1/zola-v0.17.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf -

      - name: Build do Site
        run: ./zola build --output-dir public --base-url ${{ steps.pages.outputs.base_url }}/

      - name: Upload do Site
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
