name: Publicar blog

on:
  push:
    branches:
      - main

jobs:
  publicar:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: shalzz/zola-deploy-action@v0.14.0
        env:
          BUILD_ONLY: true

      - name: Publicar
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
