name: Publicar blog com Zola

on:
  push:
    branches:
      - main

jobs:
  publicar:
    name: Publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zola
        uses: shalzz/zola-deploy-action@v0.13.0
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
